#!/usr/bin/env bash
# Run Nginx as Nginx part 2
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart#!/usr/bin/env bash
# Fix this container so that Nginx is running as user "nginx"
pkill apache2
chown -R nginx /etc/nginx
chmod 770 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
